name: spedread
base: core22
adopt-info: spedread
grade: stable
confinement: strict
compression: lzo
architectures:
  - build-on: amd64
  - build-on: armhf
  - build-on: arm64

slots:
  spedread:
    interface: dbus
    bus: session
    name: com.github.Darazaki.Spedread

environment:
  # WORKAROUND: Add python modules in Snap to search path
  PYTHONPATH: ${SNAP}/usr/lib/python3/dist-packages:$PYTHONPATH

apps:
  spedread:
    command: usr/bin/spedread
    extensions: [gnome]
    plugs:
      - home
      - raw-usb
      - bluez
      - audio-playback
      - network
      - network-bind
      - network-status
      - optical-drive
      - removable-media
    common-id: com.github.Darazaki.Spedread
    desktop: usr/share/applications/com.github.Darazaki.Spedread.desktop


parts:
  spedread:
    source: https://github.com/Darazaki/Spedread.git
    source-tag: v2.3.4
    plugin: meson
    parse-info: [usr/share/metainfo/com.github.Darazaki.Spedread.appdata.xml]
    meson-parameters:
      - --prefix=/snap/spedread/current/usr
    override-pull: |
      craftctl default
      craftctl set version=$(git describe --tags --abbrev=0)
      sed -e 's|Icon=com.github.Darazaki.Spedread|Icon=${SNAP}/usr/share/icons/hicolor/scalable/apps/com.github.Darazaki.Spedread.svg|' -i data/com.github.Darazaki.Spedread.desktop.in
    override-build: |
      craftctl default
      # WORKAROUND: Use python from search path, the path detected by meson doesn't exist when running the Snap
      sed -e '1c#!/usr/bin/env python3' -i ${CRAFT_PART_INSTALL}/snap/spedread/current/usr/bin/spedread
    organize:
      snap/spedread/current/usr: usr
